In [4]:
import torch

In [5]:
torch.__version__

'1.9.1+cpu'

In [6]:
import numpy as np

In [7]:
arr = np.array([1,2,3,4,5])

In [9]:
print(arr)

[1 2 3 4 5]


In [10]:
arr.dtype

dtype('int32')

In [11]:
type(arr)

numpy.ndarray

In [12]:
torch.from_numpy(arr)

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [15]:
x = torch.from_numpy(arr)

In [16]:
type(x)

torch.Tensor

In [17]:
torch.as_tensor(arr)

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [18]:
x

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [19]:
x.dtype

torch.int32

In [21]:
arr2d = np.arange(0.0, 12.0)

In [22]:
arr2d = arr2d.reshape(4, 3)

In [23]:
x2 = torch.from_numpy(arr2d)

In [24]:
x2

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)

In [25]:
arr

array([1, 2, 3, 4, 5])

In [26]:
x

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [29]:
arr[0] = 99

In [30]:
arr

array([99,  2,  3,  4,  5])

In [31]:
x

tensor([99,  2,  3,  4,  5], dtype=torch.int32)

In [32]:
my_arr = np.arange(0, 10)

In [33]:
my_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
my_tensor = torch.tensor(my_arr)

In [35]:
my_other_tensor = torch.from_numpy(my_arr)

In [36]:
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [37]:
my_other_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [38]:
my_arr[0] = 9999

In [39]:
my_arr

array([9999,    1,    2,    3,    4,    5,    6,    7,    8,    9])

In [40]:
my_other_tensor

tensor([9999,    1,    2,    3,    4,    5,    6,    7,    8,    9],
       dtype=torch.int32)

In [41]:
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [42]:
new_arr = np.array([1,2,3])

In [43]:
new_arr.dtype

dtype('int32')

In [44]:
torch.tensor(new_arr)

tensor([1, 2, 3], dtype=torch.int32)

In [47]:
my_tensor = torch.Tensor(new_arr)

In [48]:
my_tensor.dtype

torch.float32

In [50]:
torch.empty(4,2)

tensor([[6.8664e-44, 8.1275e-44],
        [6.7262e-44, 7.7071e-44],
        [8.1275e-44, 6.7262e-44],
        [7.5670e-44, 6.4460e-44]])

In [53]:
torch.zeros(4,3, dtype=torch.int64)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [55]:
torch.ones(4,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [56]:
torch.arange(0,18,2).reshape(3,3)

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

In [58]:
torch.linspace(0,18,12).reshape(3,4)

tensor([[ 0.0000,  1.6364,  3.2727,  4.9091],
        [ 6.5455,  8.1818,  9.8182, 11.4545],
        [13.0909, 14.7273, 16.3636, 18.0000]])

In [59]:
torch.tensor([1,2,3])

tensor([1, 2, 3])

In [60]:
my_tensor = torch.tensor([1,2,3])

In [61]:
my_tensor.dtype

torch.int64

In [62]:
my_tensor.type(torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [63]:
my_tensor

tensor([1, 2, 3])

In [64]:
my_tensor = my_tensor.type(torch.int32)

In [65]:
my_tensor

tensor([1, 2, 3], dtype=torch.int32)

In [66]:
torch.rand(4,3)

tensor([[0.4456, 0.2599, 0.9670],
        [0.2384, 0.0540, 0.7192],
        [0.6757, 0.7001, 0.8722],
        [0.5074, 0.2573, 0.3834]])

In [67]:
torch.randn(4,3)

tensor([[-1.6135,  2.6068, -0.1426],
        [ 0.2586, -1.3002, -1.4811],
        [ 0.6290, -0.3256, -0.6604],
        [-0.5513, -0.9915, -0.9553]])

In [69]:
torch.randint(low=0, high=11, size=(5,5))

tensor([[7, 4, 0, 4, 4],
        [5, 8, 8, 0, 2],
        [5, 6, 5, 0, 9],
        [3, 2, 7, 0, 3],
        [5, 3, 0, 7, 2]])

In [70]:
x = torch.zeros(2,5)

In [71]:
x

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [72]:
x.shape

torch.Size([2, 5])

In [74]:
torch.rand_like(x)

tensor([[0.6355, 0.4861, 0.0426, 0.3753, 0.6180],
        [0.1977, 0.8623, 0.3614, 0.2018, 0.1146]])

In [75]:
torch.randn_like(x)

tensor([[-1.4803,  1.2278,  0.3409,  0.5315,  0.3596],
        [ 0.4961,  0.6870, -0.9386, -0.0041, -0.6601]])

In [76]:
torch.randint_like(x, low=0, high=11)

tensor([[ 7.,  2.,  1.,  2., 10.],
        [ 1., 10.,  4.,  2.,  8.]])

In [77]:
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [78]:
torch.rand(2,3)

tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])

In [79]:
torch.rand(2,3)

tensor([[0.8694, 0.5677, 0.7411],
        [0.4294, 0.8854, 0.5739]])

In [80]:
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])