In [1]:
import torch
import numpy as np

In [2]:
x = torch.arange(6).reshape(3,2)

In [3]:
x

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [4]:
type(x[1,1])

torch.Tensor

In [5]:
x[:,1]

tensor([1, 3, 5])

In [6]:
x[:,1:]

tensor([[1],
        [3],
        [5]])

In [7]:
x = torch.arange(10)

In [8]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
x.view(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [10]:
x.reshape(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [11]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
x = x.reshape(2,5)

In [13]:
x

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [14]:
x = torch.arange(10)

In [15]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
x.shape

torch.Size([10])

In [17]:
x.view(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [18]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
z = x.view(2,5)

In [20]:
z

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [21]:
x[0] = 9999

In [22]:
x

tensor([9999,    1,    2,    3,    4,    5,    6,    7,    8,    9])

In [23]:
z

tensor([[9999,    1,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [24]:
x = torch.arange(10)

In [25]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
x.shape

torch.Size([10])

In [27]:
# INFER what the 2nd dimension
x.view(2,-1)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [28]:
x.view(-1,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [29]:
a = torch.tensor([1.,2.,3.])

In [30]:
b = torch.tensor([4.,5.,6.])

In [31]:
a

tensor([1., 2., 3.])

In [32]:
a.dtype

torch.float32

In [33]:
b

tensor([4., 5., 6.])

In [34]:
a + b

tensor([5., 7., 9.])

In [35]:
torch.add(a,b)

tensor([5., 7., 9.])

In [36]:
a = a.mul(b)
# a = a * b

In [37]:
a

tensor([ 4., 10., 18.])

In [38]:
a.dot(b)

tensor(174.)

In [39]:
a = torch.tensor([[0,2,4], [1,3,5]])

In [40]:
a

tensor([[0, 2, 4],
        [1, 3, 5]])

In [41]:
b = torch.tensor([[6,7], [8,9], [10,11]])

In [42]:
b

tensor([[ 6,  7],
        [ 8,  9],
        [10, 11]])

In [43]:
a.shape

torch.Size([2, 3])

In [44]:
b.shape

torch.Size([3, 2])

In [45]:
torch.mm(a,b)

tensor([[56, 62],
        [80, 89]])

In [46]:
a @ b

tensor([[56, 62],
        [80, 89]])

In [47]:
x = torch.tensor([2.,3.,4.,5.])

In [48]:
x

tensor([2., 3., 4., 5.])

In [49]:
x.norm()

tensor(7.3485)

In [50]:
x.numel()

4

In [51]:
len(x)

4

In [52]:
a

tensor([[0, 2, 4],
        [1, 3, 5]])

In [53]:
len(a)

2

In [54]:
a.numel()

6